modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="work_together"
version="1.0.0"
displayName="work_together"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="lolde, MCreator"

[[dependencies.work_together]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




